# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme = "blowfish"
# baseURL = "https://massalia.events/"
defaultContentLanguage = "fr"
languageCode = "fr"

# pluralizeListTitles = "true" # hugo function useful for non-english languages, find out more in  https://gohugo.io/getting-started/configuration/#pluralizelisttitles

enableRobotsTXT = true
summaryLength = 0

buildDrafts = false
buildFuture = true

enableEmoji = true

googleAnalytics = "G-3G7FRRWSQZ"

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'
  quality = 80
  resampleFilter = 'Lanczos'

[imaging.exif]
  disableDate = true
  disableLatLong = true
  includeFields = ''

[minify]
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.html]
      keepWhitespace = false
    [minify.tdewolff.css]
      keepCSS2 = false

[taxonomies]
  category = "categories"
  location = "locations"
  date = "dates" 
  tag = "tags"
  author = "authors"

[permalinks]
  # Events use date-based URLs: /events/2025/01/26/event-name/
  events = "/events/:year/:month/:day/:slug/"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

    [[related.indices]]
        name = "categories"
        weight = 100

    [[related.indices]]
        name = "locations"
        weight = 80

    [[related.indices]]
        name = "dates"
        weight = 60

    [[related.indices]]
        name = "tags"
        weight = 40

    [[related.indices]]
        name = "authors"
        weight = 10

    [[related.indices]]
      applyFilter = false
      name = 'fragmentrefs'
      type = 'fragments'
      weight = 5
